### ISSUE TITLE
Likes/Thanks are not merged upon User ID merge

### ISSUE THREAD

**Issue by ghost** [mybbgroup/MyBB_Thank-you-like-plugin#147]
If we merge 2 User IDs, the merged ID will lost likes and the other ID which will remain will have its Likes.

Please add module which will support merge of likes received and given of Thank you/Like plugin upon User ID merge.

Thanks

**Comment by Cu8eeeR** [comment]
@SvePu - what do you think, is it something what can be easily fixed or not?

**Comment by Eldenroot** [comment]
@svepu - what do you think? I think this is something what is not easy to implement amd could mess up the thanks like tables

**Comment by lairdshaw** [comment]
Since @SvePu hasn't replied: unless I'm missing something, it looks like this could be implemented pretty easily by hooking into the 'admin_user_users_merge_commit' hook and running two simple queries:

* one to update the users table by incrementing the values of the tyl_unumtyls, tyl_unumrcvtyls and tyl_unumptyls columns of the destination user by the values of those columns for the source user, and

* the other to update in the g33k_thankyoulike_thankyoulike table all uids and puids which match the source user's id to that of the destination user.

**Comment by Eldenroot** [comment]
@lairdshaw - OK, feel free to open a PR. 

What if you merge two users, lets say user A and user B. User A and B added thanks to the same post. After you merge them, what happen to that post, does it lose one thanks and the author will have -1 thanks in statistic (postbit author)?

**Comment by lairdshaw** [comment]
@Eldenroot: Ah, I was missing something... more is necessary than just those three update statements. It's still doable though.

**Comment by Eldenroot** [comment]
Yes, this is something not easy but as you wrote it is doable... just cover all situations :)

**Comment by SvePu** [comment]
Maybe we could hook into this function => https://github.com/mybb/mybb/blob/dea7dd416d3df78d85fa21c7fc9874959135e2c4/admin/modules/user/users.php#L1915
